apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Create Job to restart Deployment when Configmap is updated
resources:
  - https://github.com/jaberchez/kustomize-bases/job/restart-deployment?ref=main

namespace: tom-dev

patches:
  - target:
      kind: Role
      name: restart-job
    path: patch-role.json

  - target:
      kind: RoleBinding
      name: restart-job
    path: patch-role-binding.json

  - target:
      kind: Job
      name: restart-deployment
    path: patch-job.json

# Create Configmap with the configuration from
# file ./config/tom-frontend-configmap.env
configMapGenerator:
  - name: tom-frontend-env-vars
    env: ./config/tom-frontend-configmap.env
    options:
      disableNameSuffixHash: true

#secretGenerator:
#  - name: tom-frontend-env-vars
#    env: ./config/tom-frontend-secret.env
#    options:
#      disableNameSuffixHash: true